"""Generate independent SciPy/SLSQP reference objectives for the C++ fitter tests.

Uses vendored pinned recipe data, never imports upstream Python code.
Run with the development venv (NumPy and SciPy required).
"""
from pathlib import Path
import json
import re
import numpy as np
from scipy.optimize import minimize

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / 'Plugins/LAMAudio2Expression'
SOURCE = PLUGIN / 'Source/LAMAudio2Expression/Private'
names = re.findall(r'TEXT\("([^"]+)"\)', (SOURCE / 'LAMTypes.cpp').read_text().split('return Names;')[0])
assert len(names) == 52
slots = 'PP FF TH DD kk CH SS nn RR aa E I O U'.split()
rng = np.random.default_rng(52)
lines = ['// Generated by Tools/generate_viseme_reference.py; independent SLSQP oracle.',
         'struct FVisemeReferenceCase { int32 Template; float Input[52]; float Q[52]; double Objective; };',
         'static const FVisemeReferenceCase VisemeReferenceCases[] = {']
summary = []
for template_id, template in enumerate(('OpenFaceFX', 'TalkingHead')):
    data = json.loads((PLUGIN / f'ThirdParty/VisemeTemplates/{template}.json').read_text())['recipes']
    basis = np.array([[dict(data[s]).get(n, 0) for s in slots] for n in names])
    cases = [(basis[:, j], np.ones(52)) for j in range(14)]
    cases += [(np.zeros(52), np.ones(52))]
    for _ in range(24):
        cases.append((basis @ (rng.dirichlet(np.ones(14)) * rng.random()), np.ones(52)))
        cases.append((rng.uniform(-.3, 1.3, 52), np.ones(52)))
    for _ in range(24):
        q = rng.random(52)
        q[rng.random(52) < .3] = 0
        q[names.index('tongueOut')] = 0
        cases.append((rng.random(52), q))
    for raw, q in cases:
        raw = raw.astype(np.float32)
        q = q.astype(np.float32).astype(float)
        x = np.clip(raw, 0, 1)
        x[24] *= np.float32(1) - x[26]
        x = x.astype(float)
        h = basis.T @ (q[:, None] * basis) + 1e-4 * np.eye(14)
        c = basis.T @ (q * x)
        objective = lambda v: np.sum(q * (basis @ v - x)**2) + 1e-4 * (v @ v)
        result = minimize(objective, np.zeros(14), jac=lambda v: 2 * (h @ v - c),
                          method='SLSQP', bounds=[(0, 1)] * 14,
                          constraints=[{'type': 'ineq', 'fun': lambda v: 1-v.sum(),
                                        'jac': lambda v: -np.ones(14)}],
                          options={'ftol': 1e-12, 'maxiter': 5000})
        assert result.success, result.message
        fmt = lambda a: ','.join(f'{float(v):.9e}f' for v in a)
        lines.append(f'    {{{template_id}, {{{fmt(raw)}}}, {{{fmt(q)}}}, {result.fun:.17g}}},')
    summary.append({'template': template, 'cases': len(cases), 'rank': int(np.linalg.matrix_rank(basis))})
lines.append('};')
(SOURCE / 'Tests/LAMVisemeReference.inl').write_text('\n'.join(lines) + '\n')
print(json.dumps(summary))
